<?php

declare(strict_types=1);

namespace Alnaseeg\BranchManager\Shipping;

use Alnaseeg\BranchManager\Branch\BranchResolver;
use WC_Shipping_Rate;

/**
 * Filters WooCommerce Local Pickup rates according to
 * the currently active Massar branch.
 */
final class BranchPickupFilter
{
    /**
     * WooCommerce Local Pickup method ID.
     */
    private const PICKUP_METHOD_ID = 'pickup_location';

    /**
     * Map Massar branch slugs to the exact WooCommerce
     * Local Pickup location names.
     *
     * The WooCommerce pickup rate index is intentionally
     * NOT used for branch matching.
     *
     * @var array<string, string>
     */
    private const BRANCH_PICKUP_LOCATIONS = [
        'mall-of-oman' => 'مول عمان',
        'nizwa'       => 'نزوى',
        'al-arimi'    => 'العريمي',
    ];

    public function __construct(
        private readonly BranchResolver $branchResolver
    ) {
    }

    /**
     * Register WooCommerce hooks.
     */
    public function register(): void
    {
        add_filter(
            'woocommerce_package_rates',
            [$this, 'filterRates'],
            20,
            2
        );
    }

    /**
     * Filter WooCommerce shipping rates.
     *
     * Normal shipping methods are always preserved.
     *
     * For Local Pickup:
     * - Keep only the pickup location belonging to the
     *   currently active Massar branch.
     * - Keep the original pickup rate cost/taxes.
     *
     * Safety behavior:
     * If the branch cannot be resolved, the branch is not mapped,
     * no pickup rates exist, or the matching pickup rate cannot
     * be identified, the original rates are returned unchanged.
     *
     * @param array<string, WC_Shipping_Rate> $rates
     * @param array<string, mixed>            $package
     *
     * @return array<string, WC_Shipping_Rate>
     */
    public function filterRates(
        array $rates,
        array $package
    ): array {
        unset($package);

        /*
         * Resolve the current Massar branch through the existing
         * branch system.
         *
         * No new session, cookie, or branch selector is created.
         */
        $branch = $this->branchResolver->current();

        if ($branch === null) {
            return $rates;
        }

        $branchSlug = $branch->slug();

        /*
         * Only explicitly mapped Massar branches are handled.
         */
        if (!isset(self::BRANCH_PICKUP_LOCATIONS[$branchSlug])) {
            return $rates;
        }

        $expectedPickupLocation = self::BRANCH_PICKUP_LOCATIONS[$branchSlug];

        $filteredRates = [];
        $hasPickupRates = false;
        $matchingPickupFound = false;

        foreach ($rates as $rateKey => $rate) {
            /*
             * Keep unexpected/non-standard rate values untouched.
             */
            if (!$rate instanceof WC_Shipping_Rate) {
                $filteredRates[$rateKey] = $rate;
                continue;
            }

            /*
             * Preserve every normal shipping method exactly as
             * WooCommerce generated it.
             */
            if ($rate->get_method_id() !== self::PICKUP_METHOD_ID) {
                $filteredRates[$rateKey] = $rate;
                continue;
            }

            /*
             * We found at least one Local Pickup rate.
             */
            $hasPickupRates = true;

            /*
             * WooCommerce Local Pickup stores the pickup location
             * name in the shipping rate metadata.
             */
            $pickupLocation = $rate->get_meta(
                'pickup_location',
                true
            );

            if (!is_string($pickupLocation)) {
                continue;
            }

            /*
             * Keep only the pickup location belonging to the
             * current Massar branch.
             */
            if ($pickupLocation === $expectedPickupLocation) {
                $filteredRates[$rateKey] = $rate;
                $matchingPickupFound = true;
            }
        }

        /*
         * No Local Pickup rates were generated by WooCommerce.
         *
         * Do not alter the original shipping result.
         */
        if (!$hasPickupRates) {
            return $rates;
        }

        /*
         * We could not safely identify the pickup location for
         * the current branch.
         *
         * Do not risk hiding all pickup options.
         */
        if (!$matchingPickupFound) {
            return $rates;
        }

        /*
         * Normal shipping methods + the single matching
         * Local Pickup rate are returned.
         *
         * The pickup rate itself is not modified, so its
         * WooCommerce cost/tax configuration remains intact.
         */
        return $filteredRates;
    }
}